# Generated by Django 3.2.9 on 2022-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_paypalipn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('public_key', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='public_key', max_length=250, null=True)),
                ('private_key', models.CharField(blank=True, db_collation='utf8_general_ci', db_column='private_key', max_length=250, null=True)),
            ],
            options={
                'db_table': 'wallet',
                'managed': False,
            },
        ),
    ]
