# Generated by Django 3.2.9 on 2022-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('regarding', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('flag', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'mailbox',
                'managed': False,
            },
        ),
    ]
